id: ADC5CDF35
base_file: f9204.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 07:01:18.742188
  last_modified_at: 2022-05-31 07:01:18.742195
